// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewDelivery } from "./ReviewDelivery";
import type { ReviewTarget } from "./ReviewTarget";

export type ReviewStartParams = { threadId: string, target: ReviewTarget, 
/**
 * Where to run the review:
 * - inline (default): run on the current thread
 * - detached: run on a new thread (returned in `reviewThreadId`)
 * - hybrid: run inline and also start a detached sidecar review thread
 */
delivery?: ReviewDelivery | null, };
