// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollabMessageMetadata = { author: string, role: string, status: string, mentions: Array<string>, intent: string, refs: Array<string>, priority: string, sla: string | null, taskRef: string | null, sliceRef: string | null, };
