// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "./ThreadId";

export type CollabAgentSpawnBeginEvent = { 
/**
 * Identifier for the collab tool call.
 */
call_id: string, 
/**
 * Thread ID of the sender.
 */
sender_thread_id: ThreadId, 
/**
 * Optional agent role/type requested for the spawned agent (e.g. `scout`, `builder`).
 */
agent_type: string | null, 
/**
 * Initial prompt sent to the agent. Can be empty to prevent CoT leaking at the
 * beginning.
 */
prompt: string, };
