pub mod advisor;
mod atlas;
pub mod auto_facet;
pub mod client;
pub mod daemon;
pub mod freeform;
pub mod history;
pub mod index;
mod insights;
mod metadata;
pub mod planner;
mod project;
pub mod proto;
pub mod summary;
mod workspace;

pub use atlas::AtlasFocus;
pub use atlas::atlas_breadcrumb;
pub use atlas::atlas_focus;
pub use atlas::atlas_hint_label;
pub use atlas::find_atlas_node;
pub use client::ClientOptions;
pub use client::DaemonSpawn;
pub use client::NavigatorClient;
pub use client::resolve_daemon_launcher;
pub use daemon::DaemonOptions;
pub use daemon::run_daemon;
pub use index::IndexCoordinator;
pub use planner::NavigatorSearchArgs;
pub use planner::SearchPlannerError;
pub use planner::plan_search_request;
pub use proto::SearchProfile;
pub use summary::collect_flags as navigator_flags;
pub use summary::profile_badges;
pub use summary::summarize_args;

pub const NAVIGATOR_TOOL_INSTRUCTIONS: &str = include_str!("../navigator_tool_instructions.md");
pub use advisor::HotspotMarker;
pub use advisor::format_hotspot_hint;
pub use advisor::maybe_seed_hotspot_hint;
